version: '3.4'

services:
  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Src/Services/Catalog.API/Dockerfile

  catalogdb:
    image: mongo

  basket.api:
    image: ${DOCKER_REGISTRY-}basketapi
    build:
      context: .
      dockerfile: Src/Services/Basket.Api/Dockerfile

  basketdb:
    image: redis:alpine

  ordering.api:
    image: ${DOCKER_REGISTRY-}orderingapi
    build:
      context: .
      dockerfile: Src/Services/Ordering.Api/Dockerfile

  orderdb:
    image: mcr.microsoft.com/mssql/server:2017-latest

volumes:
  mongo_data:

